// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  build: {
    transpile: ['vuetify'],
  },
  modules: ["vuetify-nuxt-module"],
  vuetify: {
    vuetifyOptions: {
      theme: {
        defaultTheme: 'light',
        themes: {
          light: {
            dark: false,
            colors: {
              primary: '#1976D2',
              secondary: '#424242',
              accent: '#82B1FF',
              error: '#FF5252',
              info: '#2196F3',
              success: '#4CAF50',
              warning: '#FFC107',
              correct: '#6aaa64',
              present: '#c9b458',
              absent: '#787c7e',
            },
          },
          dark: {
            dark: true,
            colors: {
              primary: '#2196F3',
              secondary: '#424242',
              accent: '#FF4081',
              error: '#FF5252',
              info: '#2196F3',
              success: '#4CAF50',
              warning: '#FFC107',
              correct: '#538d4e',
              present: '#b59f3b',
              absent: '#3a3a3c',
            },
          },
          oceanicLight: {
            dark: false,
            colors: {
              primary: '#00897B',
              secondary: '#26A69A',
              accent: '#00BCD4',
              error: '#FF5252',
              info: '#00ACC1',
              success: '#00C853',
              warning: '#FFB300',
              correct: '#00897B',
              present: '#26A69A',
              absent: '#78909C',
            },
          },
          oceanicDark: {
            dark: true,
            colors: {
              primary: '#26A69A',
              secondary: '#00897B',
              accent: '#00BCD4',
              error: '#FF5252',
              info: '#00ACC1',
              success: '#00C853',
              warning: '#FFB300',
              correct: '#00695C',
              present: '#00897B',
              absent: '#37474F',
            },
          },
          sunsetLight: {
            dark: false,
            colors: {
              primary: '#FF7043',
              secondary: '#FF5722',
              accent: '#FF9800',
              error: '#F44336',
              info: '#FF9800',
              success: '#8BC34A',
              warning: '#FFC107',
              correct: '#FF7043',
              present: '#FFB74D',
              absent: '#BDBDBD',
            },
          },
          sunsetDark: {
            dark: true,
            colors: {
              primary: '#FF8A65',
              secondary: '#FF7043',
              accent: '#FFB74D',
              error: '#EF5350',
              info: '#FFB74D',
              success: '#9CCC65',
              warning: '#FFD54F',
              correct: '#E64A19',
              present: '#F57C00',
              absent: '#424242',
            },
          },
        },
      },
    },
  },
})
